pipeline {
  agent any

  tools {
    jdk 'jdk-1.8'
    maven 'Maven-3.9.9'
  }

  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/ibou0188/simple-springboot-app.git', branch: 'main'
      }
    }

    stage('Build') {
      steps {
        sh 'mvn clean package'
      }
    }
  }

  post {
    success {
      archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
    }
  }
}
